#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Change this if you are using other monitor!!!!
bspc monitor Virtual1 -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color "#44475a"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#44475a"


# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Wallpaper
feh --bg-fill --randomize ~/.wallpapers/* &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# polkit
lxqt-policykit-agent &

# Picom
picom -b &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &